### ISSUE TITLE
Database is not upgraded to 13.0.3 yet.

### ISSUE THREAD

**Issue by jbreuer** [umbraco/Umbraco.Headless.Demo#5]
It seems that when the backend branch was upgraded to Umbraco 13 the database was kept on an older version. 

In this commit Umbraco.Cms.Core is upgraded from 12.0.1 to 13.0.1: https://github.com/umbraco/Umbraco.Headless.Demo/pull/4/commits/7210de1cbd96c0108b1dc3cab2e8ae5c206ce58a
The Umbraco.sqlite.db file is also upgraded in this commit.

In these commits the project is also upgraded:
13.0.2: https://github.com/umbraco/Umbraco.Headless.Demo/pull/4/commits/86f51a4674094e234352d85ad2a88f96d57542d7
13.0.3: https://github.com/umbraco/Umbraco.Headless.Demo/pull/4/commits/848b681572109c4e157c0ace99810891e45cab02

As you can see the Umbraco.sqlite.db file is not in these commits and not upgraded.

This means that if you follow the [getting started](https://github.com/umbraco/Umbraco.Headless.Demo/blob/backend/main/README.md) docs from scratch you first need to go through the upgrade step.

![image](https://github.com/umbraco/Umbraco.Headless.Demo/assets/5444597/00e149af-17ae-4e70-87bf-f3e62861c48d)

**Comment by jbreuer** [comment]
If you upgrade an SQLite database the Umbraco.sqlite.db file won't be saved until you close the application. If you go through an upgrade always stop the application before doing a commit. Than Umbraco.sqlite.db will be part of your changes. See this for example: https://github.com/jbreuer/Umbraco-OpenIdConnect-Example/commit/9352cfd5e102b8ea4f74cc9d294ffa44fb5a7f1d

**Comment by mattbrailsford** [comment]
This should now be updated in commit 34ba47eff0066973d55379e48274742013ae2a5a

Thanks for letting us know 👍
